### ISSUE TITLE
Breadcrumbs for filters applied in Classic Form

### ISSUE THREAD

**Issue by ehenneken** [adsabs/bumblebee#1253]
Currently, the results page for a query submitted through the Classic Form does not show breadcrumbs. By default, the Classic Form applies the filter `database:astronomy` and it would be helpful if this filter is represented by a breadcrumb. The same applies to the other filters in the Classic Form (`Refereed only` and `Articles only`).

**Comment by aaccomazzi** [comment]
And more in general: why does BBB require the URL syntax `fq={!type%3Daqp v%3D%24fq_database}&fq_database=(database%3A"astronomy")` for facets to show up rather than the simpler `fq=database%3Aastronomy` which is currently generated by the classic form?  It's not just a matter of aesthetics as this will affect the redirection of searches from classic.  Probably a question for @romanchyla
