### ISSUE TITLE
Make Author Affiliation Max Authors Configurable

### ISSUE THREAD

**Issue by thostetler** [adsabs/bumblebee#1367]
Add option to change the max number of authors that will be shown for each bibcode.

**Comment by thostetler** [comment]
@aaccomazzi I think I understand how this param works.  What options should be shown in the dropdown? 
`1, 2, 5, 10, 50, 100, All` ?

**Comment by aaccomazzi** [comment]
Short answers:
1. We should have the default year cutoff option be 1, 2, 3, 4, 5, 10, All, with a default of 4
2. We should have the default author cutoff option be 1, 2, 3, 4, 5, 10, All with a default of 3

And we should make these be easily configurable options in BBB since the guidelines can change at any time.

I'm writing more info below for posterity. the main use case for the author-affiliation form is to create reports that can be submitted with proposals to the NSF.  The current guidelines for these reports are listed here:
https://www.nsf.gov/publications/pub_summ.jsp?ods_key=papp
https://www.nsf.gov/pubs/policydocs/pappg18_1/index.jsp

Basically they state that the publication window should be 48 months (so if we select by year I would go for current year - 4 years to be safe), but no general guidelines are given about a cutoff on the number of authors.  This means that the choice of where we should do a cut in the author list at position N is left to the individual call for proposal.  I took a look at the recent astronomy proposal applications and didn't find any clear guidance in the recent calls, but found this in the Astronomy & Astrophysics Research Grants instructions (https://www.nsf.gov/pubs/2016/nsf16574/nsf16574.htm):

> Co-Author Listings: In the required Collaborators & Other Affiliations single-copy document, proposals should list for the PI, co-PI, and Senior Personnel only the first three (3) authors on multi-authored papers (> 3 authors) published during the 48 months preceding the submission of the proposal (this amends Proposal & Award Policies & Procedures Guide (PAPPG) II.C.1.e). If the proposing individual is one of the first three authors on a paper, then only the other two authors should be listed. Instructions in PAPPG II.C.1.e having to do with the listing of Co-Editors, Graduate Advisors, and Postdoctoral Sponsors are unchanged.
