### ISSUE TITLE
Implement another backend communication object

### ISSUE THREAD

**Issue by vsudilov** [adsabs/bumblebee#335]
I think its worthwhile to implement another Request object in bumblebee; using ApiRequestObject as a the one object responsible for all communication to the backend feels a bit odd to me; 

I think a symptom of this is that currently, all of the accounts endpoints are tied to the API version ("v1"), when logically they are separate and makes no sense to version them with the API. Passing authorization tokens also doesn't really make sense in the context of account maintenance operations IMO.

Maybe it's possible to inherit from a base RequestObject, and ApiRequestObject/AccountRequestObject would be descendants?

Thoughts @romanchyla @aholachek ?

**Comment by romanchyla** [comment]
discussed, resolved, it was a diferent issue - if i'm wrong, please reopen

notes: the request object is  a simple container, it doesn't limit the destination - but this object should always be of one class; so that all methods can expect the same behaviour

some of the headers don't indeed make sense; that's why we have (and should have more) of the mediators - those guys are constructing different ajax requests (api_request is NOT an ajax request itself)
