### ISSUE TITLE
Breadcrumb gone after hitting back button

### ISSUE THREAD

**Issue by ehenneken** [adsabs/bumblebee#485]
Maybe related to #476? I did a search "bibstem:JGRE" and generated a concept cloud afterwards. In this cloud I was intrigues by "sheepbed" (who wouldn't be?), so I selected it and hit "Apply filter to search". In the resulting list I wanted to know where "sheepbed" was mentioned, so I went into the first abstract. I saw nothing, so I hit the back button. Back at the results list, the breadcrumb was gone. 

It turned out that "sheepbed" was mentioned in the fulltext. So, no snippets when we generate a list via Concept Cloud filtering?

**Comment by aaccomazzi** [comment]
Note: the backbutton in question is the browser's back button.  If one uses the "back to results" button in BB things work ok.

I think that handling the wordcloud selection as a facet is good, but it would be nice to show the snippets.  Am I asking for too much?

**Comment by romanchyla** [comment]
actually, i'm afraid you are right, it is too hard, we don't highlight things that come from the filters; --  the cloud could put those words in the main query (but then again, it is not good if you have selected many of them) - not mentioning the expenses associated with a totally different query just because of the highlighter

perhaps we could introduce a logical condition?

```
if number_of_selected_words < 3:
   update_q # here you have highlights
else:
   update_fq # here you have breadcrumbs
```

the breadcrumbs disappears when we don't have the auxiliary informaiton about the query; but i'm already planning to improve it (it basically happens for any saved url)

**Comment by aaccomazzi** [comment]
I would prefer to solve this in a more consistent way.  And in this context, "this" means enabling highlights for certain classes of facets.  This came up in the past when discussing highlighting authors (either from facets or fielded searches) and grant ids.  

If I understand correctly the limitation seems to be that we use hl.q to be the same as q and all facets right now go in fq.  In that case the solution would be to have some logic which selectively adds terms to hl.q from a selected list of facets.

**Comment by romanchyla** [comment]
But we are not highlighting author fields, nor do we highlight matches from
property, keywords etc.

The understanding is correct, but the proposed solution will not work
consistently. The intelligence has to remain with the satellites (ie.
individual facet has to update hl.q (the small difficulty to solve is then
avoid having hl.q present in all queries - cause that is very expensive)

Having said that, it is possible to do - but I'm seriously questioning the
reason 'why'. I don't believe that every  feature is worth adding (ie.
across the board) - if some users are requesting highlights for properties
field, it doesn't mean we should force everybody to see them.

btw: if you selected Accomazzi from the list of facet names, why would you
want us remind you that you have selected them? I find that feature
annoying because I know I have selected them, why would I want to be
reminded? This feature does not help to decide which article to read
(difference in search for: accomazzi vs author:accomazzi)




On Wed, Jul 15, 2015 at 4:44 PM, Alberto Accomazzi <notifications@github.com

**Comment by aaccomazzi** [comment]
Yeah, I agree with your argument about author facets, adding this would not be a useful feature.  In the past, I've heard users ask for highlighting the name of the author they had searched for (so this is already in q), and this got me thinking along these lines...

I think the value of highlights is in exposing search terms in the narrative part of the document (title, abstract, body, acknowledgments), so the only affected facets at this point are the concept cloud and possibly the grants.
