### ISSUE TITLE
Fix HTML markup in journal field

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#543]
We are currently escaping HTML markup in the publication field, possibly others.  See, e.g.
https://ui.adsabs.harvard.edu/#abs/2012wgl..conf...74L/abstract

**Comment by romanchyla** [comment]
this looks like a data problem, if we dont escape, then any half-extracted string could break the whole site (!)

i think if there are links in the metadata field, then we should extract them into a separate field

**Comment by aaccomazzi** [comment]
It is not a data problem but rather a data feature: all fields in our system have a limited subset of HTML elements in them, so we do not need to escape them.  If there is broken HTML the solution is to fix it in the source.

There is no good alternative to this: the links need to be inline to make sense.

**Comment by romanchyla** [comment]
you can't say it is a bug of bumblebee to protect against badly formatted data

if you insist on bbb displaying the html markup from the metadata (we do it for abtract, because i assumed that that data is sanitized - which, i realize, is a problem too) - then we have to make sure that the data that comes from solr cannot contain invalid markup

i've created a ticket for it: https://github.com/adsabs/adsdata/issues/59

**Comment by romanchyla** [comment]
@aaccomazzi please comment on that issue, which fields should be sanitized besides abstract and publication

**Comment by csgrant00** [comment]
On 8/8/15 11:41 AM, Roman Chyla wrote:
>
> @aaccomazzi <https://github.com/aaccomazzi> please comment on that 
> issue, which fields should be sanitized besides abstract and publication
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/adsabs/bumblebee/issues/543#issuecomment-128992276>.
>
Certainly title.  Probably keywords too.  I'm happy to fix bad data -- 
make me a list?

-Carolyn

**Comment by aholachek** [comment]
html in the pub field is now allowed
