### ISSUE TITLE
Provide top-level page for ORCID management

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/bumblebee#704]
We should setup a BBB endpoint which provides users with information and instruction about managing their claims and profile via ADS.  This could be an enhanced version of the current user ORCID page (https://ui.adsabs.harvard.edu/#user/orcid), or a page containing instructions and a big button that takes the user through an authentication process, or something else.

Ideally this needs to work through the permutations of ADS/ORCID authentication:
- no ADS login / no ORCID authentication
- logged into ADS / no ORCID authentication
- no ADS login / authenticated with ORCID
- logged into ADS / authenticated with ORCID

**Comment by aholachek** [comment]
hi @aaccomazzi can you check #orcid-instructions in hourly and tell me if it satisfies this requirement? I actually prefer not having the instructions dynamically respond to the user's status, since then he/she might totally miss that e.g. being signed in to orcid is a requirement for the next steps.

**Comment by aaccomazzi** [comment]
looks good to me!
