### ISSUE TITLE
citation sort - not monotonic

### ISSUE THREAD

**Issue by ehenneken** [adsabs/bumblebee#806]
Example query

    year:2014

see entry 195. Even though it says `91` for the citation count in the UI, the Solr document for that paper has 92 citations.

![screen shot 2016-02-18 at 7 15 52 am](https://cloud.githubusercontent.com/assets/273358/13143105/91d9db96-d60f-11e5-971c-c78e66417a22.png)

**Comment by aholachek** [comment]
Hi edwin, when I do ["[citations]"].num_citations for this solr document I get 91, I think I was using that so I could link directly to the citation list and have the number correspond to the number of citations we had.

But you're saying I should switch to citation_count, right?

**Comment by ehenneken** [comment]
Hi Alex. Switching to citation_count would solve the problem, I think. I wonder where ` ["[citations]"].num_citations` gets its value from... because the length of the list of citations listed in the Solr document is 92 as well. I bet @romanchyla knows the answer to that question :-)

**Comment by aaccomazzi** [comment]
A little background on this:

* citation_count is a field in the solr doc which is used for sorting papers by citations.  It is computed a len(citation) when the document is sent to solr
* the [citations] syntax refers to the list of citations extracted from the citation cache, which contain those records in the citation field which solr was able to resolve (i.e. locating a record based on the bibcode in the list).  This is what is used to display the citations and to get the count which is printed in the result list.

Whenever the citation_count and ["[citations]"].num_citations values are different for a record it means that one or more bibcodes in the citation field were not found in solr.  Fixing this underlying problem is the only way to truly solve the problem, as we are otherwise forced to choose the lesser of two evils.

**Comment by aholachek** [comment]
ok @aaccomazzi should I go ahead and change the display val to citation_count and note on the citation page how many citations are unresolved? or should i wait for further discussion?

**Comment by aholachek** [comment]
this should be fixed in hourly
