### ISSUE TITLE
XHR: not needed

### ISSUE THREAD

**Issue by romanchyla** [adsabs/bumblebee#811]
Alex, please take a look at this: https://github.com/adsabs/bumblebee/pull/793/files#diff-c035ec5bdb0a7a7ddbb163ba737c2151R84

the xhr is needed only for certain requests (such as user), but is wasting data by sending cookies to others - so the bbb could specify them in the bootstrap

**Comment by aholachek** [comment]
Hi Roman, XHR == ajax (right?) so I'm not sure if I fully understand what you are saying here.
I think you are saying that xhrFields.withCredentials should be default set to false, right? 

By "specifying them in the bootstrap" I understand that to mean having a list in discovery.config.js. 
I might have thought about putting the configuration in api_targets, since that's where I currently have limit information for some of the targets. Or would it be better to move all configuration to discovery.config?

**Comment by adsabs-beer-user** [comment]
yes, the xhr should not be set (by default) and be present only for certain
requests; which those are, i don't know fully (/user, /bootstrap, some
others?)

the api_targets might be a good idea, but how to do it simply? if not
feasible, then discovery_bootstrap.js or inside the discovery.vars.js if
you want to make it easily configurable, seem to be good places

**Comment by aholachek** [comment]
Ok, I am 99% sure I understand...just to confirm, when you write "xhr" you mean to write "xhrFields.withCredentials", right? (Since xhr means XMLHttpRequest, and we are continuing to use that for all requests).

**Comment by romanchyla** [comment]
yes, 'xhrFields'
